# 基本设置
title: KDY 加密行情与 Web3 指南
SEOTitle: KDY 加密行情｜比特币价格·以太坊走势·USDT换算·OKX钱包
description: "覆盖 BTC、ETH、SOL、XRP、ADA、SUI、Pi 等币种的实时价格与图表，提供人民币兑换 USDT/USDC、USD→Solana 计算器、ETH 换算工具与 OKX/欧易钱包登录与使用教程，追踪 Notcoin、NEIRO 等热点项目与交易所资讯。"
keyword: "bitcoin price today, cryptocurrency price, 0.0001 eth to usd, usdc to usd, usd to solana calculator, ethusdt, sol price, xrp usdt, solana usdt, ada coin price, sui usdt, neiro usdt, notcoin price, pi crypto price, b9iensjcdfhzsjbf4jvxvvanuwdkeaadbn6u879kpump, 人民币兑换usdt, pi币价格, 比特币今天价格, 以太坊走势, 欧 易 中国, okx wallet login, okex 官方 网站, OKX官网, 欧意交易所, OKX交易所, OKX登录, OKX Web3钱包, 比特币价格, 以太坊价格, Sui价格, 人民币兑USDT, USDT换算人民币, 区块链钱包, Web3博客, 加密货币资讯, 数字货币行情, 去中心化金融"
url: "https://kdyvh140.github.io"
baseurl: ""
github_username:    kdyvh140
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
